name: knuffimap
description: An abstraction over `package:firebase_database`.
version: 0.0.2
homepage: https://github.com/Crazywater/knuffimap
repository: https://github.com/Crazywater/knuffimap

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  collection: ^1.14.0
  firebase_database: ^3.0.5
  meta: ^1.1.8
  rxdart: ^0.23.1

  flutter:
    sdk: flutter
