name: knuffimap
description: An abstraction over `package:firebase_database`.
version: 0.2.0
homepage: https://github.com/Crazywater/knuffimap
repository: https://github.com/Crazywater/knuffimap

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  collection: ^1.14.13
  firebase_database: ^10.0.3
  meta: ^1.2.4
  rxdart: ^0.27.5

  flutter:
    sdk: flutter
