name: knuffimap
description: An abstraction over `package:firebase_database`.
version: 0.0.1
repository: https://github.com/Crazywater/knuffimap

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  firebase_database: ^3.0.5
  rxdart: ^0.23.1

  flutter:
    sdk: flutter
