name: knuffimap
description: An abstraction over `package:firebase_database`.
version: 0.1.0
homepage: https://github.com/Crazywater/knuffimap
repository: https://github.com/Crazywater/knuffimap

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  collection: ^1.14.13
  firebase_database: ^4.4.0
  meta: ^1.2.4
  rxdart: ^0.25.0

  flutter:
    sdk: flutter
